;;; Copyright (c) 2014, Fereshta Yazdani <yazdani@cs.uni-bremen.de>
;;; All rights reserved.
;; 
;;; Redistribution and use in source and binary forms, with or without
;;; modification, are permitted provided that the following conditions are met:
;;; 
;;;     * Redistributions of source code must retain the above copyright
;;;       notice, this list of conditions and the following disclaimer.
;;;     * Redistributions in binary form must reproduce the above copyright
;;;       notice, this list of conditions and the following disclaimer in the
;;;       documentation and/or other materials provided with the distribution.
;;;     * Neither the name of the Institute for Artificial Intelligence/
;;;       Universitaet Bremen nor the names of its contributors may be used to 
;;;       endorse or promote products derived from this software without 
;;;       specific prior written permission.
;;; 
;;; THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
;;; AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
;;; IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
;;; ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
;;; LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
;;; CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
;;; SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
;;; INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
;;; CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
;;; ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
;;; POSSIBILITY OF SUCH DAMAGE.

(in-package :startup-mission)

(defvar *tf*)
(defun make-reasoning-cost-function (location axis pred threshold)
  (roslisp:ros-info (sherpa-spatial-relations) "calculate the costmap")
  (let* ((transformation (cl-transforms:pose->transform location))
         (world->location-transformation (cl-transforms:transform-inv transformation)))
    (lambda (x y)
      (let* ((point (cl-transforms:transform-point world->location-transformation
                                                   (cl-transforms:make-3d-vector x y 0)))
             (coord (ecase axis
                      (:x (cl-transforms:x point))
                      (:y (cl-transforms:y point))))
             (mode (sqrt (+  (* (cl-transforms:x point) (cl-transforms:x point))
                             (* (cl-transforms:y point) (cl-transforms:y point))))))
        (if (funcall pred coord 0.0d0)
            (if (> (abs (/ coord mode)) threshold)
                (abs (/ coord mode))
                0.0d0)
            0.0d0)))))

(defun make-bb-height-function (obj-name height)
  (sem-map-utils::get-semantic-map)
  (let* ((sem-hash (slot-value semantic-map-utils::*cached-semantic-map* 'sem-map-utils:parts))
         (dim  (slot-value (gethash obj-name sem-hash) 'sem-map-utils:dimensions)))
    (setf height (/ (cl-transforms:z dim) 2))
    (if (< height 1)
	(setf height 1.5)
	(setf height height))
    (lambda (x y)
      (declare (ignore x y))
      (list height))))

(defun make-constant-height-function (obj-name height)
  (sem-map-utils::get-semantic-map)
  (let* ((sem-hash (slot-value semantic-map-utils::*cached-semantic-map* 'sem-map-utils:parts))
         (dim  (slot-value (gethash obj-name sem-hash) 'sem-map-utils:dimensions)))
    (setf height  (+ (cl-transforms:z dim) 1))
    (lambda (x y)
      (declare (ignore x y))
      (list height))))

(defun check-right-direction(human-pose obj-pose)
  (let((human-origin (cl-transforms:origin human-pose))
       (obj-origin (cl-transforms:origin obj-pose))
       (pred NIL)
       (axis NIL))
     (format t "human origin ~a ~% obj origin ~a~%" human-origin obj-origin)
    (cond ((and (< (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (= (cl-transforms:y human-origin) (cl-transforms:y obj-origin)))
           (setf axis :Y)
           (setf pred '<))
          ((and (> (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (= (cl-transforms:y human-origin) (cl-transforms:y obj-origin)))
           (setf axis :Y)
           (setf pred '>))
          ((and (= (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (< (cl-transforms:y human-origin) (cl-transforms:y obj-origin)))
           (setf axis :X)
           (setf pred '>))
          ((and (= (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (> (cl-transforms:y human-origin) (cl-transforms:y obj-origin)))
           (setf axis :X)
           (setf pred '<))
          ((and (< (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (< (cl-transforms:y human-origin) (cl-transforms:y obj-origin))
                (and (< (- (cl-transforms:x human-origin) (cl-transforms:x obj-origin)) -1.5)
                    (> (- (cl-transforms:y human-origin) (cl-transforms:y obj-origin)) -7.0)))
           (format t "first case ~%")
           (setf axis :Y)
           (setf pred '<))
          ((and (> (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (> (cl-transforms:y human-origin) (cl-transforms:y obj-origin))
                (and (> (- (cl-transforms:x human-origin) (cl-transforms:x obj-origin)) 2.5)
                    (<= (- (cl-transforms:y human-origin) (cl-transforms:y obj-origin)) 7.0)))
           (format t "second case ~%")
           (setf axis :Y)
           (setf pred '>))
          (t (format t "error~%")))
    (list axis pred)))

(defun check-left-direction(human-pose obj-pose)
  (let((human-origin (cl-transforms:origin human-pose))
       (obj-origin (cl-transforms:origin obj-pose))
       (pred NIL)
       (axis NIL))
     (format t "human origin ~a ~% obj origin ~a~%" human-origin obj-origin)
    (cond ((and (< (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (= (cl-transforms:y human-origin) (cl-transforms:y obj-origin)))
           (setf axis :Y)
           (setf pred '>))
          ((and (> (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (= (cl-transforms:y human-origin) (cl-transforms:y obj-origin)))
           (setf axis :Y)
           (setf pred '<))
          ((and (= (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (< (cl-transforms:y human-origin) (cl-transforms:y obj-origin)))
           (setf axis :X)
           (setf pred '<))
          ((and (= (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (> (cl-transforms:y human-origin) (cl-transforms:y obj-origin)))
           (setf axis :X)
           (setf pred '>))
          (t (format t "error~%")))
    (list axis pred)))

(defun check-r-direction(human-pose obj-pose)
  (let((human-origin (cl-transforms:origin human-pose))
       (obj-origin (cl-transforms:origin obj-pose))
       (pred NIL)
       (axis NIL))
     (format t "human origin ~a ~% obj origin ~a~%" human-origin obj-origin)
    (cond ((and (< (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (< (cl-transforms:y human-origin) (cl-transforms:y obj-origin))
                (and (< (- (cl-transforms:x human-origin) (cl-transforms:x obj-origin)) -1.5)
                    (> (- (cl-transforms:y human-origin) (cl-transforms:y obj-origin)) -7.0)))
            (format t "first case ~%")
            (setf axis :Y)
            (setf pred '<))
           ((and (> (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                 (> (cl-transforms:y human-origin) (cl-transforms:y obj-origin))
                 (and (> (- (cl-transforms:x human-origin) (cl-transforms:x obj-origin)) 2.5)
                      (<= (- (cl-transforms:y human-origin) (cl-transforms:y obj-origin)) 7.0)))
            (format t "second case ~%")
            (setf axis :Y)
            (setf pred '>))          
          ((and (> (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
                (< (cl-transforms:y human-origin) (cl-transforms:y obj-origin))
                (and (<= (- (cl-transforms:x human-origin) (cl-transforms:x obj-origin)) 2.5)
                    (< (- (cl-transforms:y human-origin) (cl-transforms:y obj-origin)) -1.5)))
           (format t "third case ~%")
           (setf axis :X)
           (setf pred '>))
          (t (format t "h ~a~%"(- (cl-transforms:x human-origin) (cl-transforms:x obj-origin))) 
            (format t "sh ~a~%"(- (cl-transforms:y human-origin) (cl-transforms:y obj-origin)))
           (format t "error~%")))
    (list axis pred)))
  
(defun tf-right-direction ()
  (let((obj-ori (cl-transforms:origin (get-model-pose->relative-genius "tree05_link")))
      ;; (human-origin (cl-transforms:origin human-pose))
      ;; (obj-origin (cl-transforms:origin obj-pose))
       (pred NIL)
       (axis NIL))
    (cond ((and (plusp (cl-transforms:x obj-ori))
               (minusp (cl-transforms:y obj-ori)))
         (setf pred '>)
         (setf axis :X))
          ((and (plusp (cl-transforms:x obj-ori))
                (plusp (cl-transforms:y obj-ori)))
         (setf pred '<)
         (setf axis :X)))           
     (list axis pred)))



(defun tf-right-direction2 ()
  (let((obj-ori (cl-transforms:origin (get-model-pose->relative-genius "tree05_link")))
      ;; (human-origin (cl-transforms:origin human-pose))
      ;; (obj-origin (cl-transforms:origin obj-pose))
       (pred NIL)
       (axis NIL))
    (cond((and (plusp (cl-transforms:x obj-ori))
               (and (> (cl-transforms:y obj-ori) -41)
                    (< (cl-transforms:y obj-ori) 41)))
          (setf pred '>)
          (setf axis :Y))
         ((and (minusp (cl-transforms:x obj-ori))
               (and (> (cl-transforms:y obj-ori) -41)
                    (< (cl-transforms:y obj-ori) 41)))
          (setf pred '<)
          (setf axis :Y))
         ((and (plusp (cl-transforms:y obj-ori))
              (and (> (cl-transforms:x obj-ori) -42)
                   (< (cl-transforms:x obj-ori) 42)))
         (setf pred '>)
         (setf axis :X))
        ((and (minusp (cl-transforms:y obj-ori))
              (and (> (cl-transforms:x obj-ori) -42)
                   (< (cl-transforms:x obj-ori) 42)))
         (setf pred '<)
         (setf axis :X))) 
     (list axis pred)))
         

     
;; (defun check-the-left-direction (human-pose obj-pose)
;;   (let((human-origin (cl-transforms:origin human-pose))
;;        (obj-origin (cl-transforms:origin obj-pose))
;;        (pred NIL))
;;     (cond((> (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
;;           (setf pred '<))
;;          ((< (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
;;           (setf pred '>))
;;          ((and (= (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
;;                (minusp (cl-transforms:y obj-origin)))
;;           (setf pred '<))
;;          ((and (= (cl-transforms:x human-origin) (cl-transforms:x obj-origin))
;;                (plusp (cl-transforms:y obj-origin)))
;;           (setf pred '>))
;;   (t (format t "okay something went wrong~%")))
;;     pred))    
         
(defun make-costmap-bbox-gen (objs &key invert padding)
(force-ll objs)
 ;;(format t "objs ~a jdjddsj~%" objs)
  (when objs
    (let ((aabbs (loop for obj in (cut:force-ll objs)
                       collecting (btr:aabb obj))))
      (lambda (x y)
        (block nil
          (dolist (bounding-box aabbs (if invert 1.0d0 0.0d0))
            (let* ((bb-center (cl-bullet:bounding-box-center bounding-box))
                   (dimensions-x/2
                     (+ (/ (cl-transforms:x (cl-bullet:bounding-box-dimensions bounding-box)) 2)
                        padding))
                   (dimensions-y/2
                     (+ (/ (cl-transforms:y (cl-bullet:bounding-box-dimensions bounding-box)) 2)
                        padding)))
              (when (and
                     (< x (+ (cl-transforms:x bb-center) dimensions-x/2))
                     (> x (- (cl-transforms:x bb-center) dimensions-x/2))
                     (< y (+ (cl-transforms:y bb-center) dimensions-y/2))
                     (> y (- (cl-transforms:y bb-center) dimensions-y/2)))
                (return (if invert 0.0d0 1.0d0)))))))))) 

(defun make-costmap-bbox-gen-obj (obj-name &key invert padding)
  (let*((sem-hash (slot-value semantic-map-utils::*cached-semantic-map* 'sem-map-utils:parts))
        (sem-obj (gethash obj-name sem-hash))
        (pose (slot-value sem-obj 'cram-semantic-map-utils:pose))
        (dim (slot-value sem-obj 'cram-semantic-map-utils:dimensions))
        (z/2-dim (/ (cl-transforms:z (slot-value sem-obj 'cram-semantic-map-utils:dimensions)) 2)))
    (lambda (a b)
      (block nil
        (let*((bb-center (cl-transforms:make-3d-vector 
                           (cl-transforms:x (cl-transforms:origin pose)) (cl-transforms:y (cl-transforms:origin pose)) (+ (cl-transforms:z (cl-transforms:origin pose)) z/2-dim)))
              (dim-x/2 (+ (/ (cl-transforms:x dim) 2) padding))
              (dim-y/2 (+ (/ (cl-transforms:y dim) 2) padding)))
          (format t "edli~%")
          (format t "x ~a and y~a~%" a b)
          (format t "bb-center ~a~%" bb-center)
          (format t "~a~%" (+ (cl-transforms:x bb-center) dim-x/2))
          (format t "~a~%" (+ (cl-transforms:x bb-center) dim-y/2))
          (when (and
                 (< a (+ (cl-transforms:x bb-center) dim-x/2))
                 (> a (- (cl-transforms:x bb-center) dim-x/2))
                 (< b (+ (cl-transforms:y bb-center) dim-y/2))
                 (> b (- (cl-transforms:y bb-center) dim-y/2)))
            (format t "-----> a ~a~% and y~a~%" a b)
            (return (if invert 0.0d0 1.0d0))))))))

(defun make-location-cost-function (loc std-dev)
  (let ((loc (cl-transforms:origin loc)))
    (make-gauss-cost-function loc `((,(float (* std-dev std-dev) 0.0d0) 0.0d0)
                                    (0.0d0 ,(float (* std-dev std-dev)))))))

(defun get-object-pose->semantic-map (object &optional (semantic-map (sem-map-utils::get-semantic-map)))
  (let((obj (sem-map-utils::semantic-map-part semantic-map object)))
       (slot-value obj 'sem-map-utils:pose)))

(defun get-genius-pose->world-model (frame-id)
  (roslisp:ros-info (STARTUP-MISSION::cost-functions) "Get the position of a link in relation with the world_frame")
 ;; (roslisp-utilities:startup-ros)
  (let((*tf* (make-instance 'cl-tf:transform-listener)))
    (cl-transforms:transform->pose (cl-tf:lookup-transform *tf* "world" frame-id :timeout 2.0))))
  ;;  (cl-transforms-stamped:transform->pose transform)))

(defun get-model-pose->relative-genius (frame-id)
  (roslisp:ros-info (STARTUP-MISSION::cost-functions) "Get the position of a link in relation with the world_frame")
 ;; (roslisp-utilities:startup-ros)
  (let((*tf* (make-instance 'cl-tf:transform-listener)))
    (cl-transforms:transform->pose (cl-tf:lookup-transform *tf* frame-id "genius_link" :timeout 2.0))))

(defun semantic-map->geom-object (geom-objects object-name)
(let*((geom-list geom-objects)
      (object NIL))
  (loop while (and (/= (length geom-list) 0) (equal object NIL))
	do(cond ((string-equal (slot-value (car geom-list) 'sem-map-utils:name) object-name)
		 (setf object (car geom-list)))
		(t (setf geom-list (cdr geom-list)))))
(list object)))
	  
(defun semantic-map->geom-objects (geom-objects param object-pose)
;;  (format t "method semantic map ~a ~%" geom-objects)
(let*((geom-list geom-objects)
      (objects NIL))
  (loop while (/= (length geom-list) 0) 
	do;;(format t "inital ~a~%" geom-list)
     (cond ((and T
                (compare-distance-of-objects (slot-value (car geom-list) 'sem-map-utils:pose) object-pose param))
      ;;      (format t "tester ~a~%" geom-list)
		 (setf objects
           (append objects (list (first geom-list))))
            (setf geom-list (cdr geom-list)))
          (t (setf geom-list (cdr geom-list)))))
 ;; (format t "und objects sind ~a~%" objects)
objects))

(defun compare-distance-of-objects (genius_position pose param)
  (let*((vector (cl-transforms:origin pose))
        (x-vec (cl-transforms:x vector))
        (y-vec (cl-transforms:y vector))
        (z-vec (cl-transforms:z vector))
        (ge-vector (cl-transforms:origin genius_position))
        (x-ge (cl-transforms:x ge-vector))
        (y-ge (cl-transforms:y ge-vector))
        (z-ge (cl-transforms:z ge-vector))
        (test NIL))
    (if (> param (sqrt (+ (square (- x-vec x-ge))
                          (square (- y-vec y-ge))
                          (square (- z-vec z-ge)))))
     (setf test T)
     (setf test NIL))
    test))

(defun return-first-value (values)
  (setf fvalue (first values))
    fvalue)

(defun return-second-value (values)
  (setf svalue (second values))
    svalue)
